# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: suhovius/kbot
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.1.0-db6d0bb"
  os: linux
  arch: amd64
secret:
  name: "kbot"
  tokenKey: token
  tokenName: TELE_TOKEN
